### ISSUE TITLE
demoflexfold suggestions

### ISSUE THREAD

**Issue by thumbert** [rydmike/rydmike.github.io#1]
Hi,

I love your demoflexfold webapp.  Can you consider enabling keyboard navigation (Page Up/PageDown/ Up arrow/Down arrow) on the page?  Also text highlighting for copying is not possible.  Mouse scrolling works. 

Thank you,
Tony

**Comment by rydmike** [comment]
Hi Tony,

Thanks for the early feedback, much appreciated! 😃 

Regarding the keyboard navigation, totally yes, it is good idea and I need and want that too. I have to study a bit how the Flutter framework implements it on its own widgets and copy it. Also just saw a fresh medium article on this topic. You might have noticed that navigation with tab and shift+tab works for jumping between Toggles (toggle with spacebar) and value Sliders with left/right arrows too, on the content on eg the Settings page. Definitely have to have that on the menu and buttons that are a part of the Flexfold scaffold widget as well.

Regarding selecting text in the content of the demo web app. Yeah, that is a Flutter thing caused by the fact that it is not drawing the text presentation the way a normal web app does. By default all text in a Flutter Web app cannot be selected nor copied. You have to use a special SelectableText() widget instead of plain Text().

I talked about this in my feedback to Google's Flutter team as well, since it is one things we noticed on how people reacted and interacted with Flutter web app. It's was not really on their roadmap to make it standard thing. The thinking and recommendation for now is that devs will and should use SelectableTest when there is need to be able to select and copy text in the app (or provide a copy text button/icon). In Desktop apps you cannot really paint and copy UI text either, unless it is designed to be able to do so. The rationale for the Flutter Web app is a bit the same, but I agree with you, it makes it feel less Web like. Being able to paint and copy text is expected behavior on a Web app, even if its not on a mobile device/desktop so it should really do that to feel more "web native".

It would of course be possible to make a small custom widget that outputs Text() on devices/desktop and SelectableText() on web builds an use it for your Text outputs in any app. That could be used to make a Web build of the same app feel more Web like. 
Hmm... maybe it will give it a try, just not sure how much more expensive using SelectableText is compared Text, I'll ask around and see what people say about it, and compare their implementations myself too, just to see what the render cost impact might be.

Thanks again for the input! 
Mike
